=== markroper/edpanel/ETL/docs/api-developer-guide-1.6.0/plugin/plugin.xsd
<xs:schema targetNamespace="http://plugin.powerschool.pearson.com"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns="http://plugin.powerschool.pearson.com"
           elementFormDefault="qualified">

	<xs:element name="plugin">
		<xs:complexType>
			<xs:all>
				<xs:element name="registration" type="registrationType" minOccurs="0" maxOccurs="1" nillable="false"/>
				<xs:element name="oauth" type="oauthType" minOccurs="0" maxOccurs="1" nillable="false" />
                <xs:element name="access_request" type="accessRequestType" minOccurs="0" maxOccurs="1" nillable="false" />
				<xs:element name="openid" type="openidType" minOccurs="0" maxOccurs="1" nillable="false" />
				<xs:element name="saml" type="samlType" minOccurs="0" maxOccurs="1" nillable="false" />                            
				<xs:element name="links" type="linksTypeWebLink" minOccurs="0" maxOccurs="1" nillable="false" />
				<xs:element name="publisher" type="publisherDetail" minOccurs="1" maxOccurs="1" nillable="false" />
				<xs:element name="autoinstall" type="autoinstallType" minOccurs="0" maxOccurs="1" nillable="false" />
				<xs:element name="identityAttribute" type="identityAttributeDetail" minOccurs="0" maxOccurs="1" nillable="false" />
			</xs:all>
			<xs:attribute name="name" use="required" type="string40strict"/>
			<xs:attribute name="version" type="string20"/>
			<xs:attribute name="description" type="string256"/>
			<xs:attribute name="class" type="string256"/>
			<xs:attribute name="deletable" use="optional" type="xs:boolean" default="true" />
		</xs:complexType>
	</xs:element>

	<xs:complexType name="autoinstallType">
		<xs:all>
			<xs:element name="autoenable" type="autoenableType" minOccurs="0" maxOccurs="1" nillable="false" />
			<xs:element name="autoregister" type="autoregisterType" minOccurs="0" maxOccurs="1" nillable="false" />
			<xs:element name="autoredeploy" type="autoredeployType" minOccurs="0" maxOccurs="1" nillable="false" />
		</xs:all>
		<xs:attribute name="required" use="optional" type="xs:boolean" default="false" />
	</xs:complexType>

	<xs:complexType name="autoenableType">
		<xs:attribute name="required" use="optional" type="xs:boolean" default="false" />
	</xs:complexType>

	<xs:complexType name="autoregisterType">
		<xs:attribute name="required" use="optional" type="xs:boolean" default="false" />
	</xs:complexType>

	<xs:complexType name="autoredeployType">
	</xs:complexType>

	<xs:complexType name="oauthType">
		<xs:all>
			<xs:element name="consumer" type="consumerType" minOccurs="0" maxOccurs="1" nillable="false" />
		</xs:all>
		<xs:attribute name="account_token" use="optional" type="string256" />
	</xs:complexType>

	<xs:complexType name="accessRequestType">
		<xs:sequence>
			<xs:element name="field" maxOccurs="unbounded" minOccurs="0">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:string">
							<xs:attribute name="table" type="string30" use="required" />
							<xs:attribute name="field" type="string30" use="required" />
							<xs:attribute name="access" type="requestedAccessType"
								use="required" />
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
		</xs:sequence>	
	</xs:complexType>

    <xs:simpleType name="requestedAccessType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="ViewOnly" />
            <xs:enumeration value="FullAccess" />
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="consumerType">
		<xs:all>
			<xs:element name="url" type="string1000strict" />
		</xs:all>
	</xs:complexType>

	<xs:complexType name="openidType">
		<xs:sequence>
			<xs:element name="links" type="linksTypeOpenID" minOccurs="1" maxOccurs="1" nillable="false" />    
		</xs:sequence>
		<xs:attribute name="host" type="string256strict" use="required"/> 
		<xs:attribute name="port" type="xs:unsignedShort" use="optional" default="443" />        
	</xs:complexType>

	<xs:complexType name="samlType">
		<xs:sequence>
  		 	<xs:element name="links" type="linksTypeSAML" minOccurs="0" maxOccurs="1" nillable="false"/>
			<xs:element name="attributes" type="samlAttributesType" minOccurs="0" maxOccurs="1" nillable="false" />   
			<xs:element name="permissions" type="permissionsType" minOccurs="0" maxOccurs="1" nillable="false"/>     
            <xs:element name="inline_authentication" type="inlineAuthenticationDetail" minOccurs="0" maxOccurs="1" nillable="false" />
		</xs:sequence>
		<xs:attribute name="name" use="required" type="string256" />
	    <xs:attribute name="entity-id" use="optional" type="string1000strict" />
		<xs:attribute name="base-url" use="optional" type="string1000strict" />
		<xs:attribute name="metadata-url" use="optional" type="string1000strict" />
		<xs:attribute name="nameid-format" use="optional" type="nameid_format_enum" />
		<xs:attribute name="idp-name" use="optional" type="string256" />
		<xs:attribute name="idp-entity-id" use="optional" type="string1000strict" />
		<xs:attribute name="idp-metadata-url" use="optional" type="string1000strict" />
	</xs:complexType>

	<xs:complexType name="linksTypeOpenID">
		<xs:sequence>
			<xs:element name="link" type="linkTypeOpenID" minOccurs="1" maxOccurs="unbounded" nillable="false" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="linksTypeWebLink">
		<xs:sequence>
			<xs:element name="link" type="linkTypeWebLink" minOccurs="1" maxOccurs="unbounded" nillable="false" />
		</xs:sequence>
	</xs:complexType>    

	<xs:complexType name="linksTypeSAML">
		<xs:sequence>
			<xs:element name="link" type="linkTypeSAML" minOccurs="1" maxOccurs="unbounded" nillable="false" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="linkTypeOpenID">
		<xs:sequence>
			<xs:element name="ui_contexts" type="uiContextsType" minOccurs="1" maxOccurs="1" nillable="false" />
		</xs:sequence>
		<xs:attribute name="title" use="optional" type="string256" />
		<xs:attribute name="display-text" use="required" type="string100strict"/>
		<xs:attribute name="path" use="optional" type="string1000strict" default="/"/>
	</xs:complexType>

	<xs:complexType name="linkTypeWebLink">
		<xs:sequence>
			<xs:element name="ui_contexts" type="uiContextsType" minOccurs="1" maxOccurs="1" nillable="false" />
		</xs:sequence>
		<xs:attribute name="title" use="optional" type="string256" />
		<xs:attribute name="display-text" use="required" type="string100strict"/>
		<xs:attribute name="path" use="required" type="string1000strict"/>
	</xs:complexType>

	<xs:complexType name="linkTypeSAML">
		<xs:sequence>
			<xs:element name="ui_contexts" type="uiContextsType" minOccurs="1" maxOccurs="1" nillable="false" />
		</xs:sequence>
		<xs:attribute name="title" use="optional" type="string256" />
		<xs:attribute name="display-text" use="required" type="string100strict"/>
		<xs:attribute name="path" use="optional" type="string1000strict" default="/"/>
	</xs:complexType>

	<xs:complexType name="samlAttributesType">    
		<xs:sequence>
			<xs:element name="user" type="samlUserAttributeType" minOccurs="1" maxOccurs="unbounded" nillable="false" /> 	
		</xs:sequence>
	</xs:complexType>   

	<xs:complexType name="samlUserAttributeType">
		<xs:sequence>
			<xs:element name="attribute" type="samlAttributeType" minOccurs="1" maxOccurs="unbounded" nillable="false" />
		</xs:sequence>
		<xs:attribute name="type" use="required" type="user_type_enum" />
	</xs:complexType>

	<xs:complexType name="samlAttributeType">    
		<xs:attribute name="name" use="required" type="string256" />
		<xs:attribute name="attribute-name" use="optional" type="string256" />
		<xs:attribute name="attribute-value" use="optional" type="string256" />
		<xs:attribute name="extension" use="optional" type="string256" />
	</xs:complexType>   

	<xs:complexType name="uiContextsType">
		<xs:sequence>
			<xs:element name="ui_context" type="uiContextType" minOccurs="1" maxOccurs="unbounded" nillable="false" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="uiContextType">
		<xs:attribute name="id" use="required" type="ui_context_enum" />
	</xs:complexType>

	<xs:complexType name="permissionsType">
		<xs:sequence>
			<xs:element name="permission" type="permissionType" minOccurs="1" maxOccurs="unbounded" nillable="false" />
		</xs:sequence>        
	</xs:complexType>

	<xs:complexType name="permissionType">
		<xs:attribute name="name" use="required" type="string100strict" />
		<xs:attribute name="value" use="required" type="string100strict" />
		<xs:attribute name="description" use="required" type="string1000strict" />
	</xs:complexType>

	<xs:complexType name="registrationType">
		<xs:sequence>
			<xs:element name="callback-data" type="xs:string" minOccurs="0" maxOccurs="1" nillable="false"/>			
			<xs:element name="parameter" type="parameterType" minOccurs="0" maxOccurs="unbounded" nillable="false"/>
		</xs:sequence>
		<xs:attribute name="url" use="required" type="string1000strict"/>
	</xs:complexType>
	
	<xs:complexType name="parameterType" mixed="true">		
		<xs:attribute name="name" type="string256"/>
	</xs:complexType>

	<xs:complexType name="publisherDetail">
		<xs:sequence>
			<xs:element name="contact" type="contactDetail" minOccurs="1" maxOccurs="1" nillable="false" />            
		</xs:sequence>
		<xs:attribute name="name" type="string100strict" use="required" /> 
	</xs:complexType>

	<xs:complexType name="contactDetail">
		<xs:attribute name="phone" use="optional" type="string20" />
		<xs:attribute name="email" use="required" type="string40strict" />
	</xs:complexType>

    <xs:complexType name="identityAttributeDetail">
        <xs:sequence>
            <xs:element name="entity" type="entityDetail" minOccurs="0" maxOccurs="unbounded" nillable="false" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="entityDetail">
        <xs:attribute name="name" use="required" type="string256strict" />
        <xs:attribute name="attribute" use="required" type="string256strict" />
    </xs:complexType>

    <xs:complexType name="inlineAuthenticationDetail">
        <xs:sequence>
            <xs:element name="user_types" type="userTypesDetail" minOccurs="1" maxOccurs="1" nillable="false" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="userTypesDetail">
        <xs:sequence>
            <xs:element name="user_type" type="userTypeDetail" minOccurs="0" maxOccurs="4" nillable="false" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="userTypeDetail">
        <xs:attribute name="name" use="required" type="user_type_enum" />
        <xs:attribute name="new-window" use="optional" type="xs:boolean" default="true"/>
    </xs:complexType>

	<xs:simpleType name="string20">
		<xs:restriction base="xs:string">
			<xs:maxLength value="20" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="string30">
		<xs:restriction base="xs:string">
			<xs:maxLength value="30" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="string40">
		<xs:restriction base="xs:string">
			<xs:maxLength value="40" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="string40strict">
		<xs:restriction base="xs:string">
			<xs:minLength value="1" />
			<xs:maxLength value="40" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="string100">
		<xs:restriction base="xs:string">
			<xs:maxLength value="100" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="string100strict">
		<xs:restriction base="xs:string">
			<xs:minLength value="1" />
			<xs:maxLength value="100" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="string256">
		<xs:restriction base="xs:string">
			<xs:maxLength value="256" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="string256strict">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>        
			<xs:maxLength value="256"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="string1000">
		<xs:restriction base="xs:string">
			<xs:maxLength value="1000" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="string1000strict">
		<xs:restriction base="xs:string">
			<xs:minLength value="1" />
			<xs:maxLength value="1000" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="uri1000">
		<xs:restriction base="xs:anyURI">
			<xs:maxLength value="1000" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="ui_context_enum">
		<xs:restriction base="xs:string">
			<xs:enumeration value="admin.header"/>
			<xs:enumeration value="admin.left_nav"/>   
			<xs:enumeration value="teacher.header"/>
			<xs:enumeration value="guardian.header"/>
			<xs:enumeration value="student.header"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="user_type_enum">
		<xs:restriction base="xs:string">
			<xs:enumeration value="admin"/>
			<xs:enumeration value="teacher"/>
			<xs:enumeration value="guardian"/>
			<xs:enumeration value="student"/>
		</xs:restriction>
	</xs:simpleType>    

	<xs:simpleType name="nameid_format_enum">
		<xs:restriction base="xs:string">
			<xs:enumeration value="unspecified"/>
			<xs:enumeration value="transient"/>
			<xs:enumeration value="persistent"/>
		</xs:restriction>
	</xs:simpleType>

</xs:schema>

=== markroper/edpanel/ETL/docs/api-developer-guide-1.6.0/examples/exam/OpenSamlSP/spring-security-saml-plugin.xml
<?xml version="1.0" encoding="UTF-8"?>
<plugin xmlns="http://plugin.powerschool.pearson.com"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation='http://plugin.powerschool.pearson.com plugin.xsd'
        name="springsecuritysaml"
        version="1.0"
        description="spring security saml integration">

  <saml
		name="springsecuritysaml" 
		entity-id="springsecuritysaml"
		base-url="http://localhost:8080/"
		metadata-url="http://localhost:8080/spring-security-saml2-sp/saml/metadata/alias/defaultAlias" >

	
    <links>	   
      <link title="OpenSaml SP" display-text="SpringSecurity SAML" path="http://localhost:8080/spring-security-saml2-sp/saml/login/alias/defaultAlias?disco=true">
        <ui_contexts>
          <ui_context id="admin.header" />
		  <ui_context id="admin.left_nav"/>
		  <ui_context id="teacher.header" />
          <ui_context id="student.header" />
          <ui_context id="guardian.header" />
        </ui_contexts>
      </link>
    </links>
	
	<attributes>
		<user type="admin">
			<attribute name="role"/>
			<attribute name="FIRST_NAME"/>
			<attribute name="LAST_NAME" />
			<attribute name="LASTFIRST" />
			<attribute name="SCHOOLID" />

		</user>	
		<user type="teacher">
			<attribute name="FIRST_NAME" />
			<attribute name="LAST_NAME" />
			<attribute name="LASTFIRST" />
			<attribute name="SCHOOLID" />
			<attribute name="institutions" attribute-value="name" />			
		</user>			
		<user type="student">
			<attribute name="FIRST_NAME" />
			<attribute name="institutions" attribute-value="name" />			
		</user>
		<user type="guardian">
			<attribute name="FIRSTNAME" />
			<attribute name="LASTNAME" />
			<attribute name="institutions" attribute-value="alternate_school_number" />	
			<attribute name="students" attribute-value="dcid" />				

		</user>
    </attributes>
		<permissions group-name="AGroup">
			<permission name="P1" description="Permission 1" value="PERM_1" />
			<permission name="P2" description="Permission 2" value="PERM_2" />
			<permission name="P3" description="Permission 3" value="PERM_3" />
		</permissions>

  </saml>  
  
  <publisher name="Pearson PowerSchool">
    <contact email="publisher@example.com" />
  </publisher>  
  
</plugin>
